### ISSUE TITLE
Ubuntu: Issues with build

### ISSUE THREAD

**Issue by ARao0123** [y-256/libdivsufsort#19]
I'm trying to build the library from source code on Ubuntu.
The steps I followed are listed below:

- Got the zip from github, unpacked it. (step 1 in readme)
- mkdir build    <-- **What is the purpose of this?**
   cd build   (step2 in readme)
- I skip step 3 because I don't want to change the default installation location.
- Now, step 4 says compile the package using "make" command. **My system has make installed. But there's no makefile. Are we supposed to write it?**

**Comment by akamiru** [comment]
You already closed this topic but for reference: cmake is a tool that can generate multiple project files e.g. Makefiles or visual studio projects. If you want to install in the default location use

    cmake -DCMAKE_BUILD_TYPE="Release" ..

If you want to change it pass the CMAKE_INSTALL_PREFIX parameter:

     cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="/usr/local" ..

this generates the Makefile that you can then use with `make`.

The purpose of `mkdir build` is to build the library in a clean directory in order to not pollute the source code folder.
